pub(crate) struct FixtureCase {
    pub(crate) name: &'static str,
    pub(crate) client: &'static str,
    pub(crate) fixture: &'static str,
    pub(crate) target: &'static str,
    pub(crate) preserved: &'static [&'static str],
    pub(crate) adapter: &'static [&'static str],
}

pub(crate) const CLIENT_FIXTURES: &[FixtureCase] = &[
    FixtureCase {
        name: "claude-basic",
        client: "claude",
        fixture: "tests/fixtures/claude/settings.json",
        target: ".claude/settings.json",
        preserved: &["permissions", "Notification"],
        adapter: &["ANTHROPIC_BASE_URL", "ANTHROPIC_AUTH_TOKEN"],
    },
    FixtureCase {
        name: "claude-machine-shaped",
        client: "claude",
        fixture: "tests/fixtures/claude/settings-machine-shaped.json",
        target: ".claude/settings.json",
        preserved: &["statusLine", "enabledPlugins", "autoCompactEnabled"],
        adapter: &["https://fixture-gateway.example", "fixture-secret"],
    },
    FixtureCase {
        name: "codex-basic",
        client: "codex",
        fixture: "tests/fixtures/codex/config.toml",
        target: ".codex/config.toml",
        preserved: &["[history]", "model_providers.existing"],
        adapter: &["model_providers.rewire", "wire_api = \"responses\""],
    },
    FixtureCase {
        name: "codex-machine-shaped",
        client: "codex",
        fixture: "tests/fixtures/codex/config-machine-shaped.toml",
        target: ".codex/config.toml",
        preserved: &[
            "[features]",
            "[mcp_servers.docs]",
            "[projects.\"/workspace/aster\"]",
        ],
        adapter: &[
            "model_providers.rewire",
            "experimental_bearer_token = \"fixture-secret\"",
            "profiles.rewire",
        ],
    },
    FixtureCase {
        name: "opencode-jsonc",
        client: "opencode",
        fixture: "tests/fixtures/opencode/opencode.jsonc",
        target: ".config/opencode/opencode.jsonc",
        preserved: &["Operator-owned comment", "theme", "existing"],
        adapter: &["@ai-sdk/openai-compatible", "{file:"],
    },
    FixtureCase {
        name: "opencode-official-shaped",
        client: "opencode",
        fixture: "tests/fixtures/opencode/opencode-official-shaped.jsonc",
        target: ".config/opencode/opencode.jsonc",
        preserved: &["$schema", "coder-model", "instructions"],
        adapter: &[
            "@ai-sdk/openai-compatible",
            "https://fixture-gateway.example",
        ],
    },
    FixtureCase {
        name: "hermes-basic",
        client: "hermes",
        fixture: "tests/fixtures/hermes/config.yaml",
        target: ".hermes/config.yaml",
        preserved: &["features:", "existing:"],
        adapter: &["key_env: REWIRE_TOKEN", "transport: chat_completions"],
    },
    FixtureCase {
        name: "hermes-official-shaped",
        client: "hermes",
        fixture: "tests/fixtures/hermes/config-official-shaped.yaml",
        target: ".hermes/config.yaml",
        preserved: &["terminal:", "compression:", "fallback_providers:"],
        adapter: &[
            "api: https://fixture-gateway.example",
            "key_env: REWIRE_TOKEN",
        ],
    },
    FixtureCase {
        name: "openclaw-basic",
        client: "openclaw",
        fixture: "tests/fixtures/openclaw/openclaw.json",
        target: ".openclaw/openclaw.json",
        preserved: &["gateway", "existing"],
        adapter: &["models", "singleValue", "openai-completions"],
    },
    FixtureCase {
        name: "openclaw-official-shaped",
        client: "openclaw",
        fixture: "tests/fixtures/openclaw/openclaw-official-shaped.json",
        target: ".openclaw/openclaw.json",
        preserved: &["existing-proxy", "~/workspace", "coder-model"],
        adapter: &["rewire", "singleValue", "https://fixture-gateway.example"],
    },
];
